[project]
name = "recommendation-system"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "alembic>=1.14.0",
    "fastapi>=0.115.6",
    "fireducks>=1.1.3",
    "sqlalchemy>=2.0.36",
    "uvicorn>=0.32.1",
]
